### ISSUE TITLE
Error on packaging

### ISSUE THREAD

**Issue by OP-Gonzalo** [spayne/GameLiftStarterPlugin#3]
The following 2 errors have appeared when trying to package the server:
UATHelper: Packaging (Linux): ld.lld: error: unable to find library -laws-cpp-sdk-gamelift-server
UATHelper: Packaging (Linux): clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by spayne** [comment]
Thanks.    I included the libraries for WindowsServers but not Linux, but I can look into that today.

My focus was on getting the WindowsServer working because I see this project as a way to get started in deploying servers and so I expected Windows builds to be dominant.  Do you normally deploy Windows, Linux or both kinds of servers?  e.g. if you don't do WindowsServers, are you interested in Linux only features?

**Comment by spayne** [comment]
I pushed the Linux libraries.   This will fix the linker issue you found when packaging a linux server.

To use it:
1. cd into your Plugins/GameLiftServerSDK
2. git pull
3. package the linux server (e.g. in the editor, select Platforms/Linux/PackageProject with the server target selected).

I tested this as follows:
1. with the new library, it built the package without complaint
2. I then used WSL and ran the packaged server to ensure it wasn't missing libraries - it ran but warned that it wasn't registering with gamelift this is expected because of the command line parameter to connect wasn't specified.
3. I then ran the server again with the commandline -withgamelift.   This started but complained when it noticed it couldn't connect to gamelift.   This was expected since I was just testing locally without their servers up.

Anyway, if you do the pull, you should get past the issue you raised.
